apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: node-red-http
  namespace: node-red
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`home.local`) && PathPrefix(`/node-red`)
      services:
        - name: node-red
          port: 1880
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: node-red-stripprefix
  namespace: node-red
spec:
  stripPrefix:
    prefixes:
      - /node-red
