apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: infra
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: infra
subjects:
- kind: ServiceAccount
  name: tailscale
  namespace: infra
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io 