apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificates.cert-manager.io
spec:
  group: cert-manager.io
  names:
    kind: Certificate
    listKind: CertificateList
    plural: certificates
    shortNames:
    - cert
    - certs
    singular: certificate
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              secretName:
                type: string
              duration:
                type: string
              renewBefore:
                type: string
              issuerRef:
                type: object
                properties:
                  name:
                    type: string
                  kind:
                    type: string
                  group:
                    type: string
              dnsNames:
                type: array
                items:
                  type: string
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterissuers.cert-manager.io
spec:
  group: cert-manager.io
  names:
    kind: ClusterIssuer
    listKind: ClusterIssuerList
    plural: clusterissuers
    singular: clusterissuer
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              acme:
                type: object
                properties:
                  email:
                    type: string
                  server:
                    type: string
                  privateKeySecretRef:
                    type: object
                    properties:
                      name:
                        type: string
                  solvers:
                    type: array
                    items:
                      type: object
                      properties:
                        http01:
                          type: object
                          properties:
                            ingress:
                              type: object
                              properties:
                                class:
                                  type: string
    served: true
    storage: true 