apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-detector-app
  namespace: home-assistant
  labels:
    app: bear-detector-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bear-detector-app
  template:
    metadata:
      labels:
        app: bear-detector-app
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: bear-detector-app
        image: homelabratory.azurecr.io/bear-detector-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3030
          name: http
        env:
        - name: PORT
          value: "3030"
        - name: WEBHOOK
          valueFrom:
            secretKeyRef:
              name: bear-detector-secrets
              key: WEBHOOK
        - name: VIDEO_PATH
          value: "/input"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: bear-detector-secrets
              key: OPENAI_API_KEY
        volumeMounts:
        - name: input-data
          mountPath: /input
        - name: output-data
          mountPath: /output
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: input-data
        persistentVolumeClaim:
          claimName: home-assistant-external
          readOnly: true
      - name: output-data
        persistentVolumeClaim:
          claimName: bear-detector-output
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bear-detector-output
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
