apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-http
  namespace: home-assistant
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`home.local`)
      services:
        - name: home-assistant
          port: 8123
      middlewares:
        - name: strip-prefix