apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: home-assistant-config
    files:
      - configuration.yaml
