apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - pvc.yaml
  - traefik-crds.yaml
  - ingress.yaml
  - configmap.yaml
