apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
  labels:
    name: home-assistant 

---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
    - port: 8123
      targetPort: 8123