apiVersion: v1
kind: Service
metadata:
  name: bear-detector-app
  labels:
    app: bear-detector-app
spec:
  type: ClusterIP
  ports:
  - port: 3030
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: bear-detector-app